# -*- coding: utf-8 -*-
"""covid_limeira_extact_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1npS23t-KC1UoSJd4vZ2SG__46m1I9rkG
"""

!pip install scrapy
!pip install pytesseract Pillow
!apt-get install tesseract-ocr tesseract-ocr-por

# obter URL da imagem do site

import os
spider_result_file = '/content/drive/MyDrive/covid_Limeira/extractor/boletim.json'

if os.path.exists(spider_result_file):
  os.remove(spider_result_file)

!scrapy runspider /content/drive/MyDrive/covid_Limeira/extractor/boletim_spider.py -o /content/drive/MyDrive/covid_Limeira/extractor/boletim.json
#!scrapy runspider -h

# some_file.py
import sys
# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, '/content/drive/MyDrive/covid_Limeira/extractor/')

import os
import json
import boletim_extractor
import pandas as pd
from datetime import datetime, timedelta, date

def get_max_date(json):
  d = pd.DataFrame(json)
  return d['date'].max()

result_file ='/content/drive/MyDrive/covid_Limeira/extractor/boletim_data.json'
last_date = date(2021, 3, 10)
all_boletim = []

if os.path.exists(result_file):
  with open(result_file) as json_file:
    all_boletim = json.load(json_file)
    last_date = datetime.strptime(get_max_date(all_boletim), '%Y-%m-%d %H:%M:%S')

print(last_date)

with open('/content/drive/MyDrive/covid_Limeira/extractor/boletim.json') as json_file:
  data = json.load(json_file)
  for d in data:
    if (datetime.strptime(d['date'], '%Y-%m-%d %H:%M:%S').date() > last_date.date()):
      boletim = boletim_extractor.extract_boletim(d['img_url'])
      if (boletim):
        #print(d['date'])
        print(boletim)
        boletim['id'] = d['id']
        boletim['date'] = d['date']
        boletim['img_url'] = d['img_url']
        all_boletim.append(boletim)

with open(result_file, 'w') as outfile:  
  json.dump(all_boletim, outfile)

from datetime import date
d0 = date(2021, 3, 11)
d1 = date.today()

delta = d1 - d0

print(delta.days)

